### ISSUE TITLE
4.0.1 breaks on load

### ISSUE THREAD

**Issue by mitchcapper** [LordBoos/discord_game#30]
```
2021-05-25 03:00:55 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform discord_game
Traceback (most recent call last):
  File "/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
    await asyncio.gather(*tasks)
  File "/homeassistant/homeassistant/helpers/entity_platform.py", line 482, in _async_add_entity
    entity.entity_id = entry.entity_id
AttributeError: can't set attribute
2021-05-25 03:00:55 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up discord_game platform for sensor
Traceback (most recent call last):
  File "/homeassistant/homeassistant/helpers/entity_platform.py", line 239, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
    await asyncio.gather(*tasks)
  File "/homeassistant/homeassistant/helpers/entity_platform.py", line 482, in _async_add_entity
    entity.entity_id = entry.entity_id
AttributeError: can't set attribute
```

**Comment by LordBoos** [comment]
I too have noticed this error today, but it does not break the integration for me. Does it break it for you?

**Comment by LordBoos** [comment]
Fixed in https://github.com/LordBoos/discord_game/releases/tag/4.0.2
