### ISSUE TITLE
[Bug] Config flow could not be loaded: {"message":"Invalid handler specified"} when trying to add "Discord Game" integration.

### ISSUE THREAD

**Issue by SimenAsphaug** [LordBoos/discord_game#58]
Logger: homeassistant.config_entries
Source: config_entries.py:858
First occurred: 20:43:32 (3 occurrences)
Last logged: 20:46:09

Error occurred loading flow for integration discord_game: Exception importing custom_components.discord_game.config_flow

Versions:
Version 6.0.1 of Discord Game
Home Assistant core 2024.6.2
Home Assistant OS 11.5

Error recieved when trying to add the integration in "Devices and Services". Integration installed successfully in HACS.

**Comment by LordBoos** [comment]
This should not happen. Did you restart your HA after updating/installing this integration?

**Comment by SimenAsphaug** [comment]
Yup. Currently debugging myself. Seems like its a bug related to async_step_user. Noe idea why this happends tho. Tried restarting HA multiple times.

**Comment by SimenAsphaug** [comment]
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/discord_game/__init__.py", line 10, in <module>
    CONFIG_SCHEMA = cv.config_entry_only_config_schema(DOMAIN)
AttributeError: module 'homeassistant.helpers.config_validation' has no attribute 'config_entry_only_config_schema'

```

**Comment by SimenAsphaug** [comment]
Upgrading Home Assistant core and OS solved the issue.

**Comment by LordBoos** [comment]
Which version of HA did you have before updating?

**Comment by SimenAsphaug** [comment]
Good question. I did post the versions in the initial description, but these might be wrong when looking back. The core version is a really new release, and is the version im on after upgrading aswell. I cant find any history on what version i was on either.

**Comment by LordBoos** [comment]
I'll close this issue then. Seems like some older version of HA might be incompatible, but I can't do anything about it without more info.
